import express from "express";
import path from "path";
import fs from "fs";
import multer from "multer";
import mammoth from "mammoth";
import { GoogleGenAI } from "@google/genai";
import { createServer as createViteServer } from "vite";

const app = express();
const PORT = 3000;

// Body parser middleware
app.use(express.json({ limit: "50mb" }));
app.use(express.urlencoded({ limit: "50mb", extended: true }));

// Configure multer for file uploads in memory
const upload = multer({
  storage: multer.memoryStorage(),
  limits: { fileSize: 10 * 1024 * 1024 }, // 10MB limit
});

// Setup Gemini AI client if api key is available
const apiKey = process.env.GEMINI_API_KEY;
let aiClient: GoogleGenAI | null = null;

if (apiKey && apiKey !== "MY_GEMINI_API_KEY") {
  try {
    aiClient = new GoogleGenAI({
      apiKey: apiKey,
      httpOptions: {
        headers: {
          "User-Agent": "aistudio-build",
        },
      },
    });
    console.log("Gemini AI Client initialized successfully.");
  } catch (err) {
    console.error("Failed to initialize Gemini AI client:", err);
  }
} else {
  console.log("No valid GEMINI_API_KEY found. Falling back to rule-based converter.");
}

// ----------------- LATEX RULE-BASED CONVERTER LOGIC -----------------
function escapeLatex(text: string): string {
  // Escapes characters which have special meaning in LaTeX
  // e.g. % $ & # _ { } ~ ^ \
  // First escape backslash itself in a unique way so we don't double escape it
  let escaped = text;
  
  // Replace backslash with a temporary token
  escaped = escaped.replace(/\\/g, "___BACKSLASH_TEMP___");
  
  // Escape standard characters
  const replacements: { [key: string]: string } = {
    "&": "\\&",
    "%": "\\%",
    "\\$": "\\$",
    "#": "\\#",
    "_": "\\_",
    "{": "\\{",
    "}": "\\}",
    "~": "\\textasciitilde{}",
    "\\^": "\\textasciicircum{}",
  };

  for (const [key, value] of Object.entries(replacements)) {
    escaped = escaped.replace(new RegExp(key, "g"), value);
  }

  // Restore backslash as standard LaTeX command backslash
  escaped = escaped.replace(/___BACKSLASH_TEMP___/g, "\\textbackslash{}");
  return escaped;
}

function localRuleBasedConvert(text: string): string {
  const lines = text.split(/\r?\n/);
  const result: string[] = [];
  
  let inItemize = false;
  let inEnumerate = false;

  // Process standard header replacements, bold, italic, code inline
  const processInline = (raw: string): string => {
    let s = escapeLatex(raw);
    
    // Bold: **text** -> \textbf{text}
    s = s.replace(/\*\*(.*?)\*\*/g, "\\textbf{$1}");
    s = s.replace(/__(.*?)__/g, "\\textbf{$1}");
    
    // Italic: *text* -> \textit{text}
    s = s.replace(/\*(.*?)\*/g, "\\textit{$1}");
    s = s.replace(/_(.*?)_/g, "\\textit{$1}");

    // Code: `text` -> \texttt{text}
    s = s.replace(/`(.*?)`/g, "\\texttt{$1}");

    return s;
  };

  result.push("% ----------------------------------------");
  result.push("% Generated by PDFLaTeX Converter (Rule-based Mode)");
  result.push("% ----------------------------------------");
  result.push("\\documentclass{article}");
  result.push("\\usepackage[utf8]{inputenc}");
  result.push("\\usepackage{amsmath}");
  result.push("\\usepackage{amsfonts}");
  result.push("\\usepackage{graphicx}");
  result.push("\\usepackage{hyperref}");
  result.push("");
  result.push("\\begin{document}");
  result.push("");

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i].trim();

    if (line === "") {
      // Empty line could end list blocks if we want, or just be a paragraph break
      if (inItemize) {
        result.push("\\end{itemize}");
        inItemize = false;
      }
      if (inEnumerate) {
        result.push("\\end{enumerate}");
        inEnumerate = false;
      }
      result.push("");
      continue;
    }

    // Check headings
    if (line.startsWith("# ")) {
      if (inItemize) { result.push("\\end{itemize}"); inItemize = false; }
      if (inEnumerate) { result.push("\\end{enumerate}"); inEnumerate = false; }
      result.push(`\\section{${processInline(line.substring(2))}}`);
      continue;
    } else if (line.startsWith("## ")) {
      if (inItemize) { result.push("\\end{itemize}"); inItemize = false; }
      if (inEnumerate) { result.push("\\end{enumerate}"); inEnumerate = false; }
      result.push(`\\subsection{${processInline(line.substring(3))}}`);
      continue;
    } else if (line.startsWith("### ")) {
      if (inItemize) { result.push("\\end{itemize}"); inItemize = false; }
      if (inEnumerate) { result.push("\\end{enumerate}"); inEnumerate = false; }
      result.push(`\\subsubsection{${processInline(line.substring(4))}}`);
      continue;
    }

    // Check bullet lists (supports -, *, •)
    const bulletMatch = line.match(/^[-*•]\s+(.*)/);
    if (bulletMatch) {
      if (inEnumerate) {
        result.push("\\end{enumerate}");
        inEnumerate = false;
      }
      if (!inItemize) {
        result.push("\\begin{itemize}");
        inItemize = true;
      }
      result.push(`  \\item ${processInline(bulletMatch[1])}`);
      continue;
    }

    // Check numbered lists (supports 1., 2., etc.)
    const enumMatch = line.match(/^\d+[\.)]\s+(.*)/);
    if (enumMatch) {
      if (inItemize) {
        result.push("\\end{itemize}");
        inItemize = false;
      }
      if (!inEnumerate) {
        result.push("\\begin{enumerate}");
        inEnumerate = true;
      }
      result.push(`  \\item ${processInline(enumMatch[1])}`);
      continue;
    }

    // Default line
    result.push(processInline(line) + " \\\\");
  }

  // Close lists if any open
  if (inItemize) {
    result.push("\\end{itemize}");
  }
  if (inEnumerate) {
    result.push("\\end{enumerate}");
  }

  result.push("");
  result.push("\\end{document}");

  return result.join("\n");
}


// ----------------- API ROUTE: PARSE DOCUMENT -----------------
app.post("/api/parse-document", upload.single("file"), async (req, res) => {
  try {
    if (!req.file) {
      return res.status(400).json({ error: "No file was uploaded." });
    }

    const { originalname, buffer } = req.file;
    const extension = path.extname(originalname).toLowerCase();
    let text = "";

    if (extension === ".txt") {
      text = buffer.toString("utf8");
    } else if (extension === ".docx") {
      const result = await mammoth.extractRawText({ buffer });
      text = result.value;
      if (result.messages && result.messages.length > 0) {
        console.log("Mammoth parsing warnings:", result.messages);
      }
    } else {
      return res.status(400).json({
        error: `Unsupported file type: ${extension}. Please upload a .txt or .docx file.`,
      });
    }

    return res.json({ text, filename: originalname });
  } catch (error: any) {
    console.error("Document parsing error:", error);
    return res.status(500).json({
      error: `Failed to extract text from document: ${error.message || error}`,
    });
  }
});


// ----------------- API ROUTE: CONVERT TO LATEX -----------------
app.post("/api/convert", async (req, res) => {
  try {
    const { text, mode, documentTitle } = req.body;

    if (!text || text.trim() === "") {
      return res.status(400).json({ error: "No text found for conversion." });
    }

    const docTitle = documentTitle && documentTitle.trim() !== "" ? documentTitle.trim() : "Document";

    // Standard converter is local and instant
    if (mode === "local" || !aiClient) {
      const latex = localRuleBasedConvert(text);
      return res.json({
        latex,
        usedAi: false,
        warning: !aiClient && mode === "ai" ? "Gemini API key is not configured. Falling back to local rule-based conversion." : undefined,
      });
    }

    // AI-Enhanced conversion using Gemini
    const prompt = `Convert the following text or raw document content into a beautiful, fully self-contained, valid LaTeX document. 

Requirements:
1. It MUST compile perfectly when pasted into a blank Overleaf or any LaTeX compiler.
2. It MUST include a standard preamble exactly containing these (or other required ones):
   \\documentclass{article}
   \\usepackage[utf8]{inputenc}
   \\usepackage{amsmath}
   \\usepackage{amsfonts}
   \\usepackage{graphicx}
   \\usepackage{hyperref}
3. The title of the document should be set to "${docTitle}" if possible (using \\title{...}, \\author{...}, \\maketitle etc).
4. The content MUST be wrapped strictly between \\begin{document} and \\end{document}.
5. You MUST escape special characters like %, $, &, #, _, {, }, ~ appropriately under the hood, BUT be extremely smart about code snippets and formula notations.
6. Identify headings, bold/italic text, lists (bullet or numbered), dividers, quotes, and map them to their correct LaTeX alternatives (like \\section{}, \\textbf{}, \\textit{}, \\begin{itemize}, \\begin{enumerate}, etc.).
7. Extremely important: If the source text contains mathematical expressions (like "x squared", "integral of e^x", "sum from i=1 to n", "sqrt(a^2 + b^2)", alpha, beta), format them nicely into LaTeX equations using amsmath (e.g. \\begin{equation}, $...$).
8. If the text has tabular structures or key-value couples, render them into standard LaTeX tables if it elevates readability.
9. Output ONLY the raw valid LaTeX document. Do NOT wrap it in any markdown codeblocks (\`\`\`latex or \`\`\`) in your response since the output must be copyable directly. Start immediately with \\documentclass.

Raw content to convert:
${text}`;

    const response = await aiClient.models.generateContent({
      model: "gemini-3.5-flash",
      contents: prompt,
    });

    let rawOutput = response.text || "";
    // Clean up if it still generates markdown block wrappers
    if (rawOutput.startsWith("```")) {
      rawOutput = rawOutput.replace(/^```[a-zA-Z0-9]*\r?\n/, "").replace(/\r?\n```$/, "");
    }
    rawOutput = rawOutput.trim();

    return res.json({
      latex: rawOutput,
      usedAi: true,
    });
  } catch (error: any) {
    console.error("Gemini conversion error:", error);
    // Graceful fallback to rule-based conversion
    const fallbackLatex = localRuleBasedConvert(req.body.text);
    return res.json({
      latex: fallbackLatex,
      usedAi: false,
      error: `Gemini AI failed: ${error.message || error}. Successfully fell back to rule-based conversion.`,
    });
  }
});

// ----------------- PROJECTS DATABASE PERSISTENCE layer -----------------
const DATA_FILE = path.join(process.cwd(), "projects.json");

async function readProjectsDb(): Promise<Record<string, any[]>> {
  try {
    if (!fs.existsSync(DATA_FILE)) {
      return {};
    }
    const content = await fs.promises.readFile(DATA_FILE, "utf-8");
    return JSON.parse(content || "{}");
  } catch (err) {
    console.error("Read DB error, returning empty:", err);
    return {};
  }
}

async function writeProjectsDb(db: Record<string, any[]>): Promise<void> {
  try {
    await fs.promises.writeFile(DATA_FILE, JSON.stringify(db, null, 2), "utf-8");
  } catch (err) {
    console.error("Write DB error:", err);
  }
}

// GET projects for email
app.get("/api/projects", async (req, res) => {
  try {
    const email = (req.query.email as string || "").trim().toLowerCase();
    if (!email) {
      return res.status(400).json({ error: "Email parameter is required." });
    }
    const db = await readProjectsDb();
    const userProjects = db[email] || [];
    return res.json({ projects: userProjects });
  } catch (err: any) {
    console.error("Fetch projects error:", err);
    return res.status(500).json({ error: err.message || "Failed to load projects." });
  }
});

// POST save project
app.post("/api/projects", async (req, res) => {
  try {
    const { email, project } = req.body;
    const cleanEmail = (email || "").trim().toLowerCase();
    if (!cleanEmail) {
      return res.status(400).json({ error: "Email is required to save projects." });
    }
    if (!project || !project.id) {
      return res.status(400).json({ error: "Valid project data is required." });
    }

    const db = await readProjectsDb();
    const userProjects = db[cleanEmail] || [];
    
    // Check if project exists to overwrite, otherwise prepend
    const existingIndex = userProjects.findIndex((p: any) => p.id === project.id);
    if (existingIndex !== -1) {
      userProjects[existingIndex] = { ...project, updatedAt: Date.now() };
    } else {
      userProjects.unshift({ ...project, updatedAt: Date.now() });
    }

    db[cleanEmail] = userProjects;
    await writeProjectsDb(db);

    return res.json({ success: true, projects: userProjects });
  } catch (err: any) {
    console.error("Save project error:", err);
    return res.status(500).json({ error: err.message || "Failed to save project." });
  }
});

// POST delete project
app.post("/api/projects/delete", async (req, res) => {
  try {
    const { email, projectId } = req.body;
    const cleanEmail = (email || "").trim().toLowerCase();
    if (!cleanEmail || !projectId) {
      return res.status(400).json({ error: "Email and projectId are required." });
    }

    const db = await readProjectsDb();
    const userProjects = db[cleanEmail] || [];
    const filtered = userProjects.filter((p: any) => p.id !== projectId);
    
    db[cleanEmail] = filtered;
    await writeProjectsDb(db);

    return res.json({ success: true, projects: filtered });
  } catch (err: any) {
    console.error("Delete project error:", err);
    return res.status(500).json({ error: err.message || "Failed to delete project." });
  }
});


// Serve frontend and route fallbacks 
async function startServer() {
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server starting on port ${PORT}`);
  });
}

startServer();
